name: All packages build

on:
  push:
    branches: [ main ]
  pull_request:
    branches:
      - '**/*'

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 20
        registry-url: 'https://npm.pkg.github.com/'
        scope: '@shiftparadigm'
    - uses: ./.github/workflows/parts/cache/

    ###########
    # BUILD
    - name: Install dependencies
      run: |
        pnpm install
    - name: Pack
      run: |
        pnpm -r dev-pack

    ###########
    # PUBLISH
    # - name: Publish npm packages to GitHub
    #   working-directory: ./
    #   run:  |
    #     find . -type f -regex ".*\.tgz" -exec npm publish "{}" --access public \;
    #   env:
    #     # Cannot publish from a PrincipleStudios github org to `@shiftparadigm/` npm scope, so this is currently failing
    #     NODE_AUTH_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
    - name: Publish npm packages to NPM
      working-directory: ./
      if: ${{ github.ref == 'refs/heads/main' }}
      run:  |
        sed -i 's_//npm.pkg.github.com/_//registry.npmjs.org/_g' ${NPM_CONFIG_USERCONFIG}
        find . -type f -regex ".*\.tgz" -exec npm publish "{}" --access public \;
      env:
        NODE_AUTH_TOKEN: "${{ secrets.NPM_TOKEN }}"